# Generated by Django 4.2.17 on 2025-09-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0003_department_abbreviation_department_counter_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_code',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Código de Referência'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user_department',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Departamento'),
        ),
    ]
