# Generated by Django 4.2.24 on 2025-09-11 09:39

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_department_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content'),
        ),
    ]
