# Generated by Django 4.2.24 on 2025-09-11 10:43

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_letter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Corpo'),
        ),
    ]
