# Generated by Django 4.2.24 on 2025-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_letter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Corpo'),
        ),
    ]
