# Generated by Django 4.2.24 on 2025-09-24 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_letter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
