# Generated by Django 4.2.27 on 2026-02-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade de negocio'),
        ),
        migrations.AlterField(
            model_name='department',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
