# Generated by Django 4.2.27 on 2026-02-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_department_business_unit_alter_department_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de custo'),
        ),
    ]
