# Generated by Django 4.2.27 on 2026-02-16 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0011_department_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Múltiplos coordenadores permitidos', related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Coordenadores'),
        ),
    ]
