# Generated by Django 4.2.27 on 2026-02-16 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0012_department_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deputy_managers',
            field=models.ManyToManyField(blank=True, help_text='Coordenadores adjuntos - mesma autoridade', related_name='deputy_managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Coordenadores Adjuntos'),
        ),
    ]
