# Generated by Django 4.2.27 on 2026-02-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_department_deputy_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='business_unit',
        ),
    ]
