# Generated by Django 4.2.27 on 2026-02-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_department_created_at_department_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='coment_rejected',
            new_name='comment_rejected',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='coment_review',
            new_name='comment_review',
        ),
    ]
