# Generated by Django 4.2.27 on 2026-03-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_remove_department_counter_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', help_text='Link direto para ação (ex: /requisicoes/123)', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('RQ_SUBMITTED', 'Requisição Submetida'), ('RQ_APPROVED_DEPT', 'Aprovada (Dept/Projeto)'), ('RQ_REJECTED_DEPT', 'Rejeitada (Dept/Projeto)'), ('RQ_SENT_PURCHASING', 'Enviada para Central'), ('RQ_APPROVED_PURCHASING', 'Aprovada (Central)'), ('RQ_REJECTED_PURCHASING', 'Rejeitada (Central)'), ('RQ_FORWARDED_DIRECTOR', 'Encaminhada para Direção'), ('RQ_APPROVED_DIRECTOR', 'Aprovada (Direção)'), ('RQ_REJECTED_DIRECTOR', 'Rejeitada (Direção)'), ('RQ_PURCHASING_EDITED', 'Editada pela Central'), ('RQ_APPROVED_FINAL', 'Aprovação Final'), ('OTHER', 'Outro')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_key',
            field=models.CharField(blank=True, help_text='Chave única para deduplicação (ex: RQ-123|RQ_SUBMITTED|user_45)', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='purchase_request_id',
            field=models.IntegerField(blank=True, help_text='ID da requisição associada', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_366c29_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_key'], name='notificatio_notific_f18220_idx'),
        ),
    ]
