# Generated by Django 4.2 on 2026-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_notification_options_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timesheet_id',
            field=models.IntegerField(blank=True, help_text='ID da timesheet associada', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('RQ_SUBMITTED', 'Requisição Submetida'), ('RQ_APPROVED_DEPT', 'Aprovada (Dept/Projeto)'), ('RQ_REJECTED_DEPT', 'Rejeitada (Dept/Projeto)'), ('RQ_SENT_PURCHASING', 'Enviada para Central'), ('RQ_APPROVED_PURCHASING', 'Aprovada (Central)'), ('RQ_REJECTED_PURCHASING', 'Rejeitada (Central)'), ('RQ_FORWARDED_DIRECTOR', 'Encaminhada para Direção'), ('RQ_APPROVED_DIRECTOR', 'Aprovada (Direção)'), ('RQ_REJECTED_DIRECTOR', 'Rejeitada (Direção)'), ('RQ_PURCHASING_EDITED', 'Editada pela Central'), ('RQ_APPROVED_FINAL', 'Aprovação Final'), ('TS_SUBMITTED', 'Timesheet Submetida'), ('TS_ACTION_TAKEN', 'Ação em Timesheet (Aprovação/Rejeição)'), ('OTHER', 'Outro')], default='OTHER', max_length=50),
        ),
    ]
