# Generated by Django 4.2.17 on 2025-08-28 16:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0003_department_abbreviation_department_counter_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
            ],
            options={
                'verbose_name': 'Actividade',
                'verbose_name_plural': 'Actividades',
                'permissions': (('view_activity', 'Can view Actividade'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido')], max_length=30, verbose_name='Estado')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e hora de registro')),
                ('date_joined', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de registro')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('total_hour', models.TimeField(blank=True, null=True, verbose_name='Total de horas')),
                ('employee', models.ForeignKey(blank=True, default='Uncategorized', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_start', models.TimeField(blank=True, null=True, verbose_name='Hora de início')),
                ('hour_end', models.TimeField(blank=True, null=True, verbose_name='Hora de fim')),
                ('hour_total', models.TimeField(blank=True, null=True, verbose_name='Hora total')),
                ('date_creation', models.DateField(default=datetime.datetime.now, verbose_name='Data')),
                ('day_status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('F', 'Feriado'), ('D', 'Dispensa')], max_length=10, verbose_name='Estado do dia')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.project')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.timesheet')),
            ],
        ),
    ]
