# Generated by Django 4.2.17 on 2025-09-02 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_department_abbreviation_department_counter_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': (('view_project', 'Can view Projeto'),), 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': (), 'permissions': (('view_task', 'Can view Tarefa'),), 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'default_permissions': (), 'permissions': (('view_timesheet', 'Can view Folha de ponto'),), 'verbose_name': 'Folha de ponto', 'verbose_name_plural': 'Folhas de ponto'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='day_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hour_end',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hour_start',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='ativo',
            field=models.BooleanField(blank=True, max_length=255, null=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='project',
            name='cod_contractor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo do Empreteiro'),
        ),
        migrations.AddField(
            model_name='project',
            name='cod_supervision',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo da Supervisão'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de custo'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='project',
            name='localization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='task',
            name='update_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_creation',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hour_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hora total'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total de horas'),
        ),
    ]
