# Generated by Django 4.2.17 on 2025-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ativo',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado'),
        ),
    ]
