# Generated by Django 4.2.17 on 2025-09-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_remove_project_ativo_project_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'default_permissions': (), 'permissions': (('view_timesheet', 'Can view Timesheet'),), 'verbose_name': 'Timesheet', 'verbose_name_plural': 'Timesheets'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_creation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timesheet.timesheet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de registro'),
        ),
    ]
