# Generated by Django 4.2.17 on 2025-09-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_timesheet_options_remove_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
    ]
