# Generated by Django 4.2.24 on 2025-09-30 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_letter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0006_activity_active_activity_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hour_total',
            new_name='hour',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador'),
        ),
    ]
