# Generated by Django 4.2.24 on 2025-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_alter_task_hour_timesheetstatuschange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de registro'),
        ),
    ]
