# Generated by Django 4.2.24 on 2025-10-31 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0009_timesheet_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='update_date',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido')], default='rascunho', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateField(null=True, verbose_name='Data de submissão'),
        ),
    ]
