# Generated by Django 4.2.24 on 2025-10-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_rename_update_date_timesheet_update_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_creation',
            new_name='create_at',
        ),
    ]
