# Generated by Django 4.2.24 on 2025-11-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_rename_date_creation_task_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
