# Generated by Django 4.2.24 on 2025-11-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_rename_create_at_task_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
