# Generated by Django 4.2.27 on 2026-01-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_alter_task_activity_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data em que o trabalho foi realizado'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateTimeField(null=True, verbose_name='Data de submissão'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
