# Generated by Django 4.2.27 on 2026-01-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0016_alter_task_created_at_alter_timesheet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data em que o trabalho foi realizado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
    ]
