# Generated by Django 4.2 on 2026-03-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0018_alter_task_created_at_alter_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário da Revisão'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('needs_improvement', 'Sugestão de Melhoria')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trancado em'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Trancado por'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('em_revisao', 'Em Revisão'), ('aprovado', 'Aprovado'), ('com_sugestoes', 'Com Sugestões'), ('com_rejeitadas', 'Com Rejeitadas')], max_length=30, verbose_name='Estado'),
        ),
    ]
