# Generated by Django 4.2 on 2026-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0019_task_review_comment_task_status_timesheet_locked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ComentÃ¡rio da RevisÃ£o'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('needs_improvement', 'SugestÃ£o de Melhoria')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data de atualizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de criaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='ObservaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('em_revisao', 'Em RevisÃ£o'), ('aprovado', 'Aprovado'), ('com_sugestoes', 'Com SugestÃµes'), ('com_rejeitadas', 'Com Rejeitadas')], max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateField(null=True, verbose_name='Data de submissÃ£o'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Data de atualizaÃ§Ã£o'),
        ),
    ]
