# Generated by Django 4.2.27 on 2026-02-18 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_project_department_project_end_date_and_more'),
        ('erp', '0014_remove_department_business_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('PROJECT', 'Project Request'), ('DEPARTMENT', 'Department Request')], help_text='Is this request for a project or for a department?', max_length=20, verbose_name='Request Context')),
                ('business_unit', models.CharField(blank=True, choices=[('AS', 'Ambiente e Social'), ('ENG', 'Engenharia'), ('ARQ', 'Arquitetura'), ('CONSU', 'Consultoria'), ('FISC', 'Fiscalização'), ('SEDE', 'Sede')], max_length=100, null=True, verbose_name='Unidade de negocio')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('required_date', models.DateField(verbose_name='Required Delivery Date')),
                ('reference_month', models.DateField(help_text='Month this request is budgeted for', verbose_name='Reference Month')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PROJECT_APPROVAL', 'Pending Project Approval'), ('PENDING_DEPARTMENT_APPROVAL', 'Pending Department Approval'), ('PENDING_PURCHASING', 'Pending Purchasing Analysis'), ('PENDING_DIRECTOR_APPROVAL', 'Pending Director Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ORDERED', 'Ordered'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, verbose_name='Urgency Level')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount')),
                ('justification', models.TextField(help_text='Why is this purchase necessary?', verbose_name='Justification')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('department', models.ForeignKey(blank=True, help_text='Required if context is DEPARTMENT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='erp.department', verbose_name='Department')),
                ('project', models.ForeignKey(blank=True, help_text='Required if context is PROJECT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='project.project', verbose_name='Project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'db_table': 'purchase_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='purchase_re_status_29c658_idx'), models.Index(fields=['context_type'], name='purchase_re_context_28e03b_idx'), models.Index(fields=['requested_by', 'status'], name='purchase_re_request_7b5762_idx')],
            },
        ),
    ]
