# Generated by Django 4.2.27 on 2026-02-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='urgency_level',
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, verbose_name='Urgency Level')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Price')),
                ('preferred_supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Preferred Supplier')),
                ('special_status', models.CharField(choices=[('NORMAL', 'Normal'), ('CONSULT', 'Under Consultation'), ('TO_DEFINE', 'To Define')], default='NORMAL', help_text='For "Sob Consulta" or "A Definir" cases', max_length=20, verbose_name='Special Status')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observations')),
                ('delivery_deadline', models.DateField(verbose_name='Delivery Deadline')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisition.purchaserequest', verbose_name='Purchase Request')),
            ],
            options={
                'verbose_name': 'Request Item',
                'verbose_name_plural': 'Request Items',
                'db_table': 'purchase_request_item',
            },
        ),
    ]
