# Generated by Django 4.2.27 on 2026-02-18 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0002_remove_purchaserequest_urgency_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('DRAFT', 'Draft'), ('PROJECT_APPROVAL', 'Awaiting Project Approval'), ('DEPARTMENT_APPROVAL', 'Awaiting Department Approval'), ('PURCHASING_ANALYSIS', 'Awaiting Purchasing Analysis'), ('DIRECTOR_APPROVAL', 'Awaiting Director Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='Current Step')),
                ('requires_project_approval', models.BooleanField(default=False, verbose_name='Requires Project Approval')),
                ('requires_department_approval', models.BooleanField(default=False, verbose_name='Requires Department Approval')),
                ('requires_director_approval', models.BooleanField(default=False, verbose_name='Requires Director Approval')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='requisition.purchaserequest', verbose_name='Purchase Request')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'approval_workflow',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Approved At')),
                ('action', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('FORWARD', 'Forwarded to Director'), ('CANCEL', 'Cancelled'), ('EDIT', 'Edited by Purchasing')], max_length=20, verbose_name='Action')),
                ('step', models.CharField(choices=[('DRAFT', 'Draft'), ('PROJECT_APPROVAL', 'Awaiting Project Approval'), ('DEPARTMENT_APPROVAL', 'Awaiting Department Approval'), ('PURCHASING_ANALYSIS', 'Awaiting Purchasing Analysis'), ('DIRECTOR_APPROVAL', 'Awaiting Director Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30, verbose_name='Step')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requisition.purchaserequest', verbose_name='Purchase Request')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requisition.approvalworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'db_table': 'approval',
                'ordering': ['-approved_at'],
                'indexes': [models.Index(fields=['purchase_request', 'approved_at'], name='approval_purchas_77ca95_idx')],
            },
        ),
    ]
