# Generated by Django 4.2.27 on 2026-02-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0003_approvalworkflow_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at'], 'permissions': [('edit_purchaserequest_purchasing', 'Can edit purchase request (purchasing level)')], 'verbose_name': 'Purchase Request', 'verbose_name_plural': 'Purchase Requests'},
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_editable_by_purchasing',
            field=models.BooleanField(default=True, help_text='Whether purchasing central can edit this request', verbose_name='Editable by Purchasing'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='last_edited_by_purchasing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Edited by Purchasing At'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='last_edited_by_purchasing_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_edited_requests', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited by Purchasing By'),
        ),
    ]
