# Generated by Django 4.2.27 on 2026-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0004_alter_purchaserequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total Amount'),
        ),
    ]
