# Generated by Django 4.2.27 on 2026-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_alter_purchaserequest_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='delivery_deadline',
            field=models.DateField(blank=True, verbose_name='Delivery Deadline'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
