# Generated by Django 4.2.27 on 2026-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_alter_purchaserequestitem_delivery_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='changes_json',
            field=models.JSONField(blank=True, help_text='Detalhes das alterações quando action == EDIT', null=True, verbose_name='Changes JSON'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='erp_reference',
            field=models.CharField(blank=True, help_text='Referência retornada pelo ERP após sincronização', max_length=200, null=True, verbose_name='ERP Reference'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='erp_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='SYNCED', help_text='Estado da sincronização com o ERP (mock)', max_length=20, verbose_name='ERP Sync Status'),
        ),
    ]
