# Generated by Django 4.2.27 on 2026-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_approval_changes_json_purchaserequest_erp_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='delivery_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Deadline'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
