# Generated by Django 4.2.27 on 2026-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0009_auto_item_price_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='reference_month',
            field=models.CharField(help_text='Month this request is budgeted for', max_length=7, verbose_name='Reference Month'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
