# Generated by Django 4.2.27 on 2026-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_alter_purchaserequest_reference_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Centro de custo associado à requisição', max_length=50, null=True, verbose_name='Cost Center'),
        ),
    ]
