# Generated by Django 4.2.27 on 2026-03-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0011_purchaserequest_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('DRAFT', 'Draft'), ('PROJECT_APPROVAL', 'Awaiting Project Approval'), ('DEPARTMENT_APPROVAL', 'Awaiting Department Approval'), ('PURCHASING_ANALYSIS', 'Awaiting Purchasing Analysis'), ('DIRECTOR_APPROVAL', 'Awaiting Director Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=30, verbose_name='Workflow Step')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OBSOLETE', 'Obsolete')], default='PENDING', max_length=20, verbose_name='Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='requisition.purchaserequest', verbose_name='Purchase Request')),
            ],
            options={
                'verbose_name': 'Purchase Request Assignment',
                'verbose_name_plural': 'Purchase Request Assignments',
                'db_table': 'purchase_request_assignment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['approver', 'status'], name='purchase_re_approve_67232f_idx'), models.Index(fields=['purchase_request', 'status'], name='purchase_re_purchas_0cde9f_idx')],
            },
        ),
    ]
