# Generated by Django 4.2.27 on 2026-03-08 23:57

import core.requisition.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0012_purchaserequestassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Category Code')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requires_director_approval', models.BooleanField(default=False, help_text='All items in this category require director approval', verbose_name='Requires Director Approval')),
                ('director_approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='If item value exceeds this, requires director approval', max_digits=12, null=True, verbose_name='Director Approval Threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.requisition.models.attachment_upload_path, verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.IntegerField(verbose_name='File Size (bytes)')),
                ('attachment_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('CONTRACT', 'Contract'), ('SPECIFICATION', 'Specification'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Attachment Type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requisition.purchaserequest', verbose_name='Purchase Request')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachment',
            },
        ),
    ]
