# Generated by Django 4.2.27 on 2026-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0013_itemcategory_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base Price'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Rate'),
        ),
    ]
