# Generated by Django 4.2.27 on 2026-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0014_purchaserequestitem_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Valor final após ajustes da Central', max_digits=12, verbose_name='Approved Total'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='iteration',
            field=models.IntegerField(default=1, help_text='Número de resubmissões', verbose_name='Iteration'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='original_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Snapshot financeiro na submissão', max_digits=12, verbose_name='Original Total'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Poupança gerada (original_total - approved_total)', max_digits=12, verbose_name='Savings Amount'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade final aprovada pela Central/Direção', max_digits=10, null=True, verbose_name='Quantidade Aprovada'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='approved_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço final negociado pela Central', max_digits=10, null=True, verbose_name='Preço Unitário Aprovado'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Bloqueia edição pelo solicitante após aprovação parcial', verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Obrigatório se o item for rejeitado', null=True, verbose_name='Motivo de Rejeição'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PROJECT_APPROVAL', 'Pending Project Approval'), ('PENDING_DEPARTMENT_APPROVAL', 'Pending Department Approval'), ('PENDING_PURCHASING', 'Pending Purchasing Analysis'), ('PENDING_DIRECTOR_APPROVAL', 'Pending Director Approval'), ('AWAITING_REQUESTER_DECISION', 'Awaiting Requester Decision'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ORDERED', 'Ordered'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaserequestassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('OBSOLETE', 'Obsolete')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
