# Generated by Django 4.2.27 on 2026-03-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0015_purchaserequest_approved_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='Ex: ITEM_UPDATED, STATUS_CHANGED, PRICE_REVISION', max_length=50, verbose_name='Action Type')),
                ('action_description', models.TextField(verbose_name='Action Description')),
                ('previous_values', models.JSONField(blank=True, help_text='Snapshot antes da alteração', null=True, verbose_name='Previous Values')),
                ('new_values', models.JSONField(blank=True, help_text='Snapshot após a alteração', null=True, verbose_name='New Values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_audits', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='requisition.purchaserequest', verbose_name='Purchase Request')),
            ],
            options={
                'verbose_name': 'Requisition Audit Log',
                'verbose_name_plural': 'Requisition Audit Logs',
                'db_table': 'requisition_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_request', 'created_at'], name='requisition_purchas_dc4860_idx')],
            },
        ),
    ]
