# Generated by Django 4.2 on 2026-03-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0016_requisitionauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Supplier Code')),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('payment_terms', models.IntegerField(default=30, help_text='Default payment terms in days', verbose_name='Payment Terms (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='preferred_supplier',
            field=models.CharField(blank=True, help_text='Nome do fornecedor caso não esteja cadastrado', max_length=200, null=True, verbose_name='Preferred Supplier (Texto)'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Vínculo com a tabela mestre de fornecedores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='requisition.supplier', verbose_name='Supplier (Cadastrado)'),
        ),
    ]
