# Generated by Django 4.2 on 2026-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0017_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='urgency_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20, verbose_name='Nível de Urgência'),
        ),
    ]
