# Generated by Django 4.2 on 2026-03-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0018_purchaserequest_urgency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='awaiting_decision_since',
            field=models.DateTimeField(blank=True, help_text='Registo de quando entrou em Awaiting Requester Decision para timeout de 48h', null=True, verbose_name='Awaiting Decision Since'),
        ),
    ]
