# Generated by Django 4.2.24 on 2025-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('cod_contractor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo do Empreteiro')),
                ('cod_supervision', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo da Supervisão')),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de custo')),
                ('localization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'permissions': (('view_project', 'Can view Projeto'),),
                'default_permissions': (),
            },
        ),
    ]
