# Generated by Django 4.2.27 on 2026-02-18 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_project_department_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administrative_staff',
            field=models.ManyToManyField(blank=True, help_text='Funcionários administrativos alocados ao projeto', related_name='administrative_projects', to=settings.AUTH_USER_MODEL, verbose_name='Administrativos'),
        ),
    ]
