# Generated by Django 4.2.27 on 2026-02-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_administrative_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='administrative_staff',
        ),
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_leader',
        ),
    ]
