# Generated by Django 4.2.27 on 2026-02-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_rename_coment_rejected_letter_comment_rejected_and_more'),
        ('project', '0004_remove_project_administrative_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='erp.department', verbose_name='Departamento Responsável'),
        ),
    ]
