# Generated by Django 4.2.27 on 2026-02-18 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ManyToManyField(blank=True, help_text='Podem aprovar requisições do projeto', related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis do Projeto'),
        ),
    ]
