# Generated by Django 4.2.27 on 2026-02-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_project_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administrative_staff',
            field=models.ManyToManyField(blank=True, help_text='Funcionários administrativos alocados ao projeto', related_name='administrative_projects', to=settings.AUTH_USER_MODEL, verbose_name='Administrativos'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Team Leader'),
        ),
    ]
