# Generated by Django 4.2.27 on 2026-01-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hold_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_days_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='used_days',
        ),
    ]
