# Generated by Django 4.2.27 on 2026-01-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_purchaseprofile_employeeworksettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworksettings',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='purchaseprofile',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeHRProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeWorkSettings',
        ),
        migrations.DeleteModel(
            name='PurchaseProfile',
        ),
    ]
