# Generated by Django 4.2 on 2026-03-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Vaga')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('responsibilities', models.TextField(verbose_name='Responsabilidades')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='Média Salarial')),
                ('education_level', models.CharField(max_length=255, verbose_name='Escolaridade Exigida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contacto')),
                ('phone', models.CharField(max_length=50, verbose_name='Número de Telemóvel')),
                ('academic_degree', models.CharField(choices=[('ensino_medio', 'Ensino Médio'), ('ensino_superior', 'Ensino Superior'), ('mestre', 'Mestre'), ('doutoramento', 'Doutoramento'), ('mba', 'MBA')], max_length=50, verbose_name='Grau Académico')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('cv_file', models.FileField(upload_to='recruitment/cvs/%Y/%m/%d/', verbose_name='CV')),
                ('other_files', models.FileField(blank=True, null=True, upload_to='recruitment/others/%Y/%m/%d/', verbose_name='Outros Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobvacancy', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'db_table': 'application',
            },
        ),
    ]
