# Generated by Django 4.2.24 on 2025-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='active',
            new_name='is_active',
        ),
    ]
